/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export type AddDepartmentMemberInRole = typeof AddDepartmentMemberInRole[keyof typeof AddDepartmentMemberInRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddDepartmentMemberInRole = {
  admin: 'admin',
  member: 'member',
} as const;
