/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export interface AIConversationSettings {
  conversationId: number;
  /** @nullable */
  knowledge?: boolean | null;
  /** @nullable */
  agent?: boolean | null;
  id?: number;
  /** @nullable */
  createAt?: string | null;
  /** @nullable */
  updateAt?: string | null;
}
