/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export interface ChangeFilePermissionsIn {
  userId: string;
  /** 是否为知识库文件 */
  isKnowledgeFile: boolean;
  /** 知识库文件的权限范围：PRIVATE、PUBLIC、DEPARTMENT */
  type: string;
}
