/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export interface CheckAvailabilityOut {
  message?: string;
  is_available: boolean;
  field: string;
}
