/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */
import type { ConversationType } from './conversationType';

export interface Conversation {
  /** @nullable */
  from?: string | null;
  /** @maxLength 255 */
  displayName: string;
  /**
   * @maxLength 255
   * @nullable
   */
  recentMessage?: string | null;
  /** @maxLength 6 */
  type: ConversationType;
  id?: number;
  /** @nullable */
  createAt?: string | null;
  /** @nullable */
  updateAt?: string | null;
  readonly members?: unknown;
  readonly groups?: unknown;
  readonly friends?: unknown;
  readonly messages?: unknown;
  readonly conversation_members?: unknown;
  readonly ai_settings?: unknown;
}
