/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

/**
 * @maxLength 6
 */
export type ConversationType = typeof ConversationType[keyof typeof ConversationType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConversationType = {
  ai: 'ai',
  group: 'group',
  friend: 'friend',
} as const;
