/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export interface CreateGroupIn {
  /**
   * @minLength 0
   * @maxLength 10
   */
  name?: string;
}
