/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export interface CreateAnnouncementIn {
  /**
   * @minLength 0
   * @maxLength 10
   */
  title: string;
  /**
   * @minLength 0
   * @maxLength 255
   */
  content: string;
}
