/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */
import type { GroupAnnouncement } from './groupAnnouncement';

export interface CreateAnnouncementOut {
  message?: string;
  announcement?: GroupAnnouncement;
}
