/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export interface Email {
  msg_id?: string;
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  content?: string | null;
  sender: string;
  recipient: string;
  /** @nullable */
  isRead?: boolean | null;
  /** @nullable */
  isArchived?: boolean | null;
  /** @nullable */
  isSpam?: boolean | null;
  /** @nullable */
  isTrashed?: boolean | null;
  /** @nullable */
  tags?: string[] | null;
  /** @nullable */
  categories?: string[] | null;
  id?: number;
  /** @nullable */
  createAt?: string | null;
  /** @nullable */
  updateAt?: string | null;
}
