/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export interface EmailAccount {
  /** @maxLength 255 */
  emailName: string;
  /** @nullable */
  canReceiveOtherDomain?: boolean | null;
  /** @nullable */
  doNotice?: boolean | null;
  /** @nullable */
  favoriteEmails?: number[] | null;
  /** @nullable */
  categories?: string[] | null;
  id?: number;
  /** @nullable */
  createAt?: string | null;
  /** @nullable */
  updateAt?: string | null;
}
