/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */
import type { FileType } from './fileType';

export interface File {
  /** @maxLength 255 */
  name: string;
  /** @maxLength 8 */
  type: FileType;
  size: number;
  /** @maxLength 100 */
  mime_type: string;
  /** @maxLength 20 */
  extension: string;
  /** @maxLength 512 */
  path: string;
  /**
   * @maxLength 512
   * @nullable
   */
  url?: string | null;
  /** @maxLength 32 */
  md5: string;
  /** @nullable */
  is_public?: boolean | null;
  /** @nullable */
  is_knowledge_file?: boolean | null;
  /** @nullable */
  is_department?: boolean | null;
  /** @nullable */
  width?: number | null;
  /** @nullable */
  height?: number | null;
  /** @nullable */
  duration?: number | null;
  /**
   * @maxLength 512
   * @nullable
   */
  thumbnail?: string | null;
  /**
   * @maxLength 50
   * @nullable
   */
  encoding?: string | null;
  /** @nullable */
  last_viewed?: string | null;
  /** @nullable */
  view_count?: number | null;
  /** @nullable */
  download_count?: number | null;
  id?: number;
  /** @nullable */
  createAt?: string | null;
  /** @nullable */
  updateAt?: string | null;
}
