/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

/**
 * @maxLength 8
 */
export type FriendRequestStatus = typeof FriendRequestStatus[keyof typeof FriendRequestStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FriendRequestStatus = {
  waiting: 'waiting',
  approved: 'approved',
  rejected: 'rejected',
} as const;
