/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */
import type { FriendRequestStatus } from './friendRequestStatus';

export interface FriendRequest {
  requesterId: number;
  targetId: number;
  /** @maxLength 512 */
  introduction: string;
  /** @maxLength 8 */
  status: FriendRequestStatus;
  id?: number;
  /** @nullable */
  createAt?: string | null;
  /** @nullable */
  updateAt?: string | null;
}
