/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export type GetApiEmailsParams = {
page?: number;
per_page?: number;
type?: string;
category?: string;
};
