/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */
import type { GroupAnnouncement } from './groupAnnouncement';
import type { PaginationOut } from './paginationOut';

export interface GetAnnouncementsOut {
  message?: string;
  announcements?: GroupAnnouncement[];
  pagination?: PaginationOut;
}
