/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export type GetApiEmailsSearchParams = {
page?: number;
per_page?: number;
search_query: string;
};
