/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */
import type { Department } from './department';
import type { PaginationOut } from './paginationOut';

export interface GetDepartmentsOut {
  message?: string;
  departments?: Department[];
  pagination?: PaginationOut;
}
