/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */
import type { Email } from './email';
import type { PaginationOut } from './paginationOut';

export interface GetEmailsOut {
  message?: string;
  emails?: Email[];
  PaginationOutSchema?: PaginationOut;
}
