/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */
import type { FriendRequest } from './friendRequest';

export interface GetFriendRequestsOut {
  message?: string;
  sent_friend_requests?: FriendRequest[];
  got_friend_requests?: FriendRequest[];
}
