/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */
import type { Friend } from './friend';

export interface GetFriendOut {
  message?: string;
  friend?: Friend;
}
