/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */
import type { GroupJoinRequest } from './groupJoinRequest';
import type { PaginationOut } from './paginationOut';

export interface GetGroupJoinRequestsOut {
  message?: string;
  requests?: GroupJoinRequest[];
  pagination?: PaginationOut;
}
