/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */
import type { Message } from './message';

export interface GetMessagesOut {
  message?: string;
  messages?: Message[];
}
