/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */
import type { User } from './user';
import type { PaginationOut } from './paginationOut';

export interface GetUsersOut {
  message?: string;
  users?: User[];
  pagination?: PaginationOut;
}
