/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */
import type { Group } from './group';
import type { PaginationOut } from './paginationOut';

export interface GetUserGroupsOut {
  message?: string;
  groups?: Group[];
  pagination?: PaginationOut;
}
