/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

/**
 * @maxLength 6
 */
export type GroupMemberRole = typeof GroupMemberRole[keyof typeof GroupMemberRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GroupMemberRole = {
  agent: 'agent',
  admin: 'admin',
  member: 'member',
  owner: 'owner',
} as const;
