/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export interface Group {
  /** @maxLength 255 */
  name: string;
  /**
   * @maxLength 512
   * @nullable
   */
  avatar?: string | null;
  id?: number;
  /** @nullable */
  createAt?: string | null;
  /** @nullable */
  updateAt?: string | null;
}
