/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */
import type { GroupMemberRole } from './groupMemberRole';

export interface GroupMember {
  userId: number;
  groupId: number;
  /**
   * @maxLength 255
   * @nullable
   */
  displayName?: string | null;
  /** @maxLength 6 */
  role: GroupMemberRole;
  id?: number;
  /** @nullable */
  createAt?: string | null;
  /** @nullable */
  updateAt?: string | null;
}
