/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export interface LoginIn {
  /**
   * @minLength 3
   * @maxLength 15
   */
  username: string;
  /**
   * @minLength 6
   * @maxLength 30
   */
  password: string;
}
