/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */
import type { MessageType } from './messageType';

export interface Message {
  conversationId: number;
  userId: number;
  /** @nullable */
  fileId?: number | null;
  /** @maxLength 6 */
  type: MessageType;
  /** @nullable */
  content?: string | null;
  id?: number;
  /** @nullable */
  createAt?: string | null;
  /** @nullable */
  updateAt?: string | null;
}
