/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export interface PaginationOut {
  page?: number;
  per_page?: number;
  pages?: number;
  total?: number;
  current?: string;
  next?: string;
  prev?: string;
  first?: string;
  last?: string;
}
