/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export type PostMessageInType = typeof PostMessageInType[keyof typeof PostMessageInType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostMessageInType = {
  text: 'text',
  stream: 'stream',
  image: 'image',
  file: 'file',
} as const;
