/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */
import type { PostMessageInType } from './postMessageInType';

export interface PostMessageIn {
  type: PostMessageInType;
  content: string;
  /** @nullable */
  fileId?: number | null;
}
