/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export type PutApiJoinRequestRequestIdStatus = typeof PutApiJoinRequestRequestIdStatus[keyof typeof PutApiJoinRequestRequestIdStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutApiJoinRequestRequestIdStatus = {
  approved: 'approved',
  rejected: 'rejected',
} as const;
