/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export interface ReceiveEmailIn {
  email_name: string;
  subject: string;
  content: string;
  recipient: string;
  sender: string;
  msg_id: string;
}
