/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateUserInUpdate {
  message?: string;
  /**
   * @minLength 3
   * @maxLength 15
   */
  displayName?: string;
  /**
   * @minLength 3
   * @maxLength 15
   */
  phoneNumber?: string;
  /**
   * @minLength 6
   * @maxLength 30
   */
  bio?: string;
  avatarId?: number;
}
