/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateAIConversationSettingsIn {
  /** 知识库设置 */
  knowledge?: boolean;
  /** 智能体设置 */
  agent?: boolean;
}
