/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export type UpdateDepartmentMemberRoleInRole = typeof UpdateDepartmentMemberRoleInRole[keyof typeof UpdateDepartmentMemberRoleInRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateDepartmentMemberRoleInRole = {
  admin: 'admin',
  member: 'member',
} as const;
