/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateUserOutStatus } from './updateUserOutStatus';
import type { UpdateUserOutRole } from './updateUserOutRole';
import type { UpdateUserOutSettings } from './updateUserOutSettings';
import type { UpdateUserOutExtraMetadata } from './updateUserOutExtraMetadata';

export interface UpdateUserOut {
  /** @maxLength 255 */
  password: string;
  /** @maxLength 20 */
  username: string;
  /** @maxLength 255 */
  displayName: string;
  /** @maxLength 255 */
  email: string;
  /**
   * @maxLength 20
   * @nullable
   */
  phoneNumber?: string | null;
  /** @nullable */
  bio?: string | null;
  /** @nullable */
  lastLoginAt?: number | null;
  /** @maxLength 9 */
  status: UpdateUserOutStatus;
  /** @maxLength 9 */
  role: UpdateUserOutRole;
  /** @nullable */
  settings?: UpdateUserOutSettings;
  /** @nullable */
  extra_metadata?: UpdateUserOutExtraMetadata;
  id?: number;
  /** @nullable */
  createAt?: string | null;
  /** @nullable */
  updateAt?: string | null;
  readonly avatar_url?: unknown;
  readonly avatar?: unknown;
  readonly profile?: unknown;
  readonly stats?: unknown;
  readonly schedules_participated?: unknown;
  readonly announcements?: unknown;
  readonly groups?: unknown;
  readonly group_invites?: unknown;
  readonly email_account?: unknown;
  readonly activity_logs?: unknown;
  readonly friendships_as_user1?: unknown;
  readonly friendships_as_user2?: unknown;
  readonly sent_friend_requests?: unknown;
  readonly got_friend_requests?: unknown;
  readonly messages?: unknown;
  readonly conversations?: unknown;
  message?: string;
}
