/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

/**
 * @maxLength 9
 */
export type UpdateUserOutStatus = typeof UpdateUserOutStatus[keyof typeof UpdateUserOutStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserOutStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  BANNED: 'BANNED',
  PENDING: 'PENDING',
  DELETED: 'DELETED',
} as const;
