/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

/**
 * @maxLength 9
 */
export type UpdateUserOutRole = typeof UpdateUserOutRole[keyof typeof UpdateUserOutRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserOutRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  GUEST: 'GUEST',
  SYSTEM: 'SYSTEM',
} as const;
