/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */

export interface UploadKnowledgeIn {
  file?: Blob;
  isPublic?: boolean;
  isKnowledgeFile?: boolean;
  isDepartment?: boolean;
}
