/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIFlask
 * OpenAPI spec version: 0.1.0
 */
import type { File } from './file';

export interface UploadKnowledgeOut {
  message?: string;
  file?: File;
}
